CREATE TABLE PRODUCTOS
(
    CODEMP          VARCHAR(3)     NOT NULL,
    CODSUC          VARCHAR(3)     NOT NULL,
    CODALM          VARCHAR(3)     NOT NULL,
    CODPROD         VARCHAR(8)     NOT NULL,
    DESPROD         VARCHAR(35)    NOT NULL,
    FRACCIONES      INT            NOT NULL,
    PREUNI          DECIMAL(12, 4) NOT NULL,
    PRECOSTO        DECIMAL(12, 4) NOT NULL,
    VERSION         INT            NOT NULL,
    ROWFECHAHORA    DATETIME2      NOT NULL,
    UPDATEFECHAHORA DATETIME2      NOT NULL,
    CONSTRAINT PK_PRODUCTOS PRIMARY KEY (CODEMP, CODSUC, CODALM, CODPROD)
);