CREATE TABLE CODIGOBARRAPROD
(
    CODEMP          VARCHAR(3)  NOT NULL,
    CODSUC          VARCHAR(3)  NOT NULL,
    CODALM          VARCHAR(3)  NOT NULL,
    CODPROD         VARCHAR(8)  NOT NULL,
    CODBAR          VARCHAR(13) NOT NULL,
    FECHAREG        DATETIME   DEFAULT 'current timestamp',
    ESTADO          TINYINT,
    UPDATEFECHAHORA DATETIME   DEFAULT GETDATE(),
    CODUSUREG       VARCHAR(6),
    CODUSUUPDATE    VARCHAR(6) DEFAULT user_name(),
    CONSTRAINT PK_CODIGOBARRAPROD PRIMARY KEY (CODEMP, CODSUC, CODALM, CODPROD, CODBAR),
    CONSTRAINT FK_PRODUCTOS FOREIGN KEY (CODEMP, CODSUC, CODALM, CODPROD)
        REFERENCES PRODUCTOS (CODEMP, CODSUC, CODALM, CODPROD)
);